### PR TITLE
Update to allow pass-through of  Request & CustomData

### PR DESCRIPTION
**Pull request by MarcoWilliamsPF**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/PlayFab/UnitySDK/pull/18" target="_blank">ReviewNinja

**Comment by pgilmorepf** [comment]
What is your feeling on large amounts of spacing changes?  I generally try to avoid them when making other changes.  I can bend either way, but I figured it was worth mentioning.

I personally strive to make sure that large amounts of spacing changes are in their own checkin - though I'm guilty of ignoring that goal as well.  In the generated code it's a particularly difficult problem.

**Comment by pgilmorepf** [comment]
Other than the spacing-changes concern, LGTM.

**Comment by MarcoWilliamsPF** [comment]
These changes have carried over from the generator now in another pull request.  So i am closing this.

**Pull request closed without merging**
