### PR TITLE
Updated Push to support custom push messages.  Support for JSON Messa…

### PR DESCRIPTION
**Pull request by MarcoWilliamsPF**
…ge and parsing said JSON for custom Sounds & Icons.  Methods for getting CustomData after push has been received.

Added  IAP  aidl,  as prep for IAP plugin work.

### CODE REVIEW

**Comment by zac-playfab** [comment]
LGTM, lets get some usage instructions in the main readme too

**Comment by JohnTube** [comment]
This looks nice.

**Comment by zac-playfab** [comment]
LGTM

**Comment by pgilmorepf** [comment]
This does not pass.
I have sent you notes via email.

**Comment by pgilmorepf** [comment]
LGTM

**Pull request merged**
