### PR TITLE
New Android Plugin Source with fixed GCM

### PR DESCRIPTION
**Pull request by MarcoWilliamsPF**

### CODE REVIEW

**Comment by JohnTube** [comment]
Finally ! 
- How did you manage to make .jar library with Android Studio ? I thought it only supported the new .aar format !
- I like the fact that a Service was chosen instead of an Activity but nothing else has changed. I'm waiting for more advanced features like the ones described [here](https://support.playfab.com/support/discussions/topics/1000053870). I know it also requires server side changes...
- I did not test if saving NotificationID in this new implementation does not collide with anything else, it shouldn't. 
- I don't know why you're [still] getting the AppIcon from the service
- Notification title should not always match the Application name ! In fact you have an unused 'Subject' field in SendPushNotification API call
- First 2 lines in SendMessage are useless.

I am available to discuss my suggestions and to help make this a better plugin : more flexible and more features-rich !

**Comment by MarcoWilliamsPF** [comment]
@JohnTube  I'll try to answer your questions.

1>   we used a gradle script to extract the classes.jar file from the aar.  This is then renamed to PlayFabUnityAndroid.jar.   See - UnityAndroidPluginSource\playfabunityplugin\build.grade  at the bottom of the script.

2>  I'll review the requests that you've made in the forum.  This update is the first phase at upgrading the plugin.  Custom JSON data is planned for Push Messages.

3> yes, the NotificationId implementation is error free.  I tested it quite extensively so there should not be any issues.

4> We are doing two things here for the AppIcon,   One,  we are allowing the Developer to change this from within Unity to have a custom icon.  I have done some setup stuff for the future of this implementation.  Currently there is an override for  initGCM allowing you to pass in a custom drawable location.  Two,  we want to support passing a custom icon specific to the notification via JSON in the message.  This part is not done yet, but we are now setup so that once we implement JSON messaging we can allow custom messages to have unique Icons.   Lastly,  the default is set to app_icon, which will by default pull from drawable.

5> Noted!  I'll make this change in my next update.

6> Noted!  I'll get them removed.  That was old code left over that I missed.  Good catch!

**Comment by pgilmorepf** [comment]
LGTM

**Comment by JohnTube** [comment]
hey @MarcoWilliamsPF 

I think the code in `PlayFabGcmListenerService.onMessageReceived(String from, Bundle data)` after these comments should be reviewed.
```//Check for message first, if this message was sent via GCM API then it will contain "message"
        //otherwise it might have been sent via AWS Simple Notification Service, in which the message is in the default key.```

As a call to SendPushNotification with 
```
{
  "Recipient": "xxx",
  "Subject": "test",
  "Message": "You have been attacked! Go defend your base!"
}
```

gives this output :

```I/PlayFabUnityAndroidPlugin(29782): Received: Bundle[{from=790239815523, default=You have been attacked! Go defend your base!, android.support.content.wakelockid=2, collapse_key=do_not_collapse}]```

so no "message" key in Bundle data from GCM notification.

**Comment by MarcoWilliamsPF** [comment]
@JohnTube. This is the expected behavior from sending GCM via playfab.   Message is only if you were to send the GCM message via.  Google API  /GCM/send. URI.   It is not anything that you'll need to worry about.  This edge case is for those using the plugin and sending GCM from outside of playfab server / services.

**Comment by JohnTube** [comment]
@MarcoWilliamsPF 
OK. Now I understand. Thanks !
It may be a little bit late but welcome to PlayFab ! @pgilmorepf too !

**Pull request merged**
