### PR TITLE
Removing a bunch of files 

### PR DESCRIPTION
**Pull request by pgilmorepf**
…that are not neccessary to publish the UnitySDK

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/PlayFab/UnitySDK/pull/11" target="_blank">ReviewNinja

**Comment by MarcoWilliamsPF** [comment]
LGTM - make sure that whatever conflict is being reported is fixed

**Comment by pgilmorepf** [comment]
I'll figure it out.

**Comment by pgilmorepf** [comment]
Calvin helped me merge it back with the main branch.

**Pull request merged**
